/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mmm;

/**
 *
 * @author steve
 */
public enum MMMLanguageProperty {
    // Dialog Titles and Messages
    ABOUT_TITLE,
    ABOUT_MESSAGE,
    
    NEW_METRO_MAP_TITLE,
    NEW_METRO_MAP_MESSAGE,
    
    NAME_TAKEN_MESSAGE,
    NAME_TAKEN_TITLE,
    
    ADD_METRO_STATION_TITLE,
    ADD_METRO_STATION_MESSAGE,
    
    // Toolbar Items
    METRO_LINES_TOOLBAR_TITLE,
    METRO_STATIONS_TOOLBAR_TITLE,
    DECOR_TOOLBAR_TITLE,
    FONT_TOOLBAR_TITLE,
    NAVIGATION_TOOLBAR_TITLE,
    APPEND_STATION_TEXT,
    REMOVE_STATION_TEXT,
    SNAP_TEXT,
    MOVE_LABEL_TEXT,
    SHOW_GRID_TEXT,
    
    // Tooltips
    ADD_LINE_TOOLTIP,
    REMOVE_LINE_TOOLTIP,
    METRO_LINE_INFO_TOOLTIP,
    ADD_METRO_STATION_TOOLTIP,
    DELETE_METRO_STATION_TOOLTIP,
    ROTATE_LABEL_TOOLTIP,
    FIND_ROUTE_TOOLTIP,
    BOLD_TOOLTIP,
    ITALIC_TOOLTIP,
    ZOOM_IN_TOOLTIP,
    ZOOM_OUT_TOOLTIP,
    SMALLER_TOOLTIP,
    LARGER_TOOLTIP,
    ADD_IMAGE_TOOLTIP,
    ADD_TEXT_TOOLTIP,
    REMOVE_ELEMENT_TOOLTIP,
    SET_IMAGE_BACKGROUND_TOOLTIP,
    SAVE_AS_TOOLTIP,
    EXPORT_TOOLTIP,
    UNDO_TOOLTIP,
    REDO_TOOLTIP,
    ABOUT_TOOLTIP,
    
    // Icons
    SAVE_AS_ICON,
    SET_IMAGE_BACKGROUND_ICON,
    REMOVE_ELEMENT_ICON,
    FIND_ROUTE_ICON,
    BOLD_ICON,
    ABOUT_ICON,
    ADD_ICON,
    REMOVE_ICON,
    ROTATE_ICON,
    PICTURE_ICON,
    ADD_IMAGE_ICON,
    EXPORT_ICON,
    ITALICS_ICON,
    LARGER_ICON,
    METRO_LINE_INFO_ICON,
    SMALLER_ICON,
    TEXT_ICON,
    ZOOM_IN_ICON,
    ZOOM_OUT_ICON,
    UNDO_ICON,
    REDO_ICON,
    
    // Recent File Stuff
    RECENT_FILE_1,
    RECENT_FILE_2,
    RECENT_FILE_3,
    RECENT_FILE_4,
    RECENT_FILE_5,
}
